plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace "com.indooratlas.flutter"
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'io.flutter:flutter_embedding_debug:1.0.0'
    implementation("com.indooratlas.android:indooratlas-android-sdk:3.7.1@aar") {
        transitive = true
    }
}
