name: indooratlas
description: Develop Flutter applications powered with the IndoorAtlas indoor positioning technology.
version: 0.0.1
homepage: https://indooratlas.com/

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.indooratlas.flutter
        pluginClass: IAFlutterPlugin
